# Generated by Django 2.2.5 on 2019-10-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='shirt description'),
            preserve_default=False,
        ),
    ]
